In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import decomposition
from sklearn.preprocessing import StandardScaler
import glob
import os
from tslearn.clustering import TimeSeriesKMeans
import copy as cp
import random
import pickle
import multiprocessing
import time
from collections import Counter
import math
from utils import extract_feature



In [2]:
class ADP:
	def __init__(self, model_path="ADP_utils/models.pkl", prob_path="ADP_utils/prob.pkl"):
		self.kmeans=pickle.load(open(model_path, 'rb'))[8]
		self.prob = pickle.load(open(prob_path, 'rb'))

	def predict(self, traj):
		feature = extract_feature(traj)
		category = self.kmeans.predict(feature)
		return self.prob[category]

In [9]:
prob  =pickle.load(open("ADP_utils/prob.pkl", 'rb'))

In [10]:
prob

defaultdict(float,
            {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0})

In [16]:
a=np.zeros((3,2))
b=np.ones((3,2))
print(a)
a-[1,0]

[[0. 0.]
 [0. 0.]
 [0. 0.]]


array([[-1.,  0.],
       [-1.,  0.],
       [-1.,  0.]])

In [17]:
a+b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])